name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  release:
    timeout-minutes: 5
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Set Release version
        run: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Set environment variables
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          body: "${{ github.event.head_commit.message }}"
          tag_name: ${{ env.VERSION }}
          target_commitish: ${{ github.ref }}
          files: |
            ./target/*.jar